# Generated by Django 5.1.7 on 2025-03-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releaase_date',
            new_name='release_date',
        ),
    ]
